// Generated by hand from the CDK stack outputs in golf-app-backend (no Amplify CLI/sandbox
// used here -- see lib/golf-app-backend-stack.ts). Re-run `cdk deploy` and update these values
// if the backend stack's Cognito/AppSync resources ever get replaced.
//
// Uses the Amplify Gen 2 "amplify_outputs" schema, which amplify_authenticator 2.7.x expects
// (password_policy/username_attributes/standard_required_attributes are Gen 2 field names --
// the older classic-CLI config shape is missing them).
const amplifyconfig = '''{
  "version": "1.3",
  "auth": {
    "user_pool_id": "us-east-1_TqzRNHT76",
    "aws_region": "us-east-1",
    "user_pool_client_id": "2kv2cb7jp711nvu6pvu4hv5vul",
    "username_attributes": ["email"],
    "standard_required_attributes": ["email"],
    "user_verification_types": ["email"],
    "password_policy": {
      "min_length": 8,
      "require_lowercase": true,
      "require_numbers": true,
      "require_symbols": false,
      "require_uppercase": false
    }
  },
  "data": {
    "url": "https://qbue4ctudzco5e76bqcuzw2q6i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_region": "us-east-1",
    "default_authorization_type": "AMAZON_COGNITO_USER_POOLS",
    "authorization_types": []
  }
}''';
